apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: app
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ["{{ .Values.command }}"]
          args: {{ .Values.args }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: NODE_ENV
              value: {{ .Values.nodeEnv }}
            - name: MONGODB_URI
              value: "mongodb://{{ .Release.Name }}-mongodb-service:{{ .Values.mongodb.port }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}